# 配置文件按如下优先级读取：
#
# 1. 当前工作目录下的 `thus-saith.toml`。
# 2. [用户配置目录][1]下的 `thus-saith/config.toml`。
# 3. 默认值（程序内嵌）。
#
# 顶层配置项未指定时，使用回退值。
#
# Configuration files are read in the following order:
#
# 1. `thus-saith.toml` in current working directory.
# 2. `thus-saith/config.toml` in [user config directory][1].
# 3. Default (embedded in the program).
#
# If a top-level configuration item is unspecified,
# the fallback value is used.
#
# [1]: https://docs.rs/dirs/6.0.0/dirs/fn.config_dir.html

[pace]
# 每字符平均用时（单位：毫秒）。
#
# - 值为 nan、inf、负数或零，且未被覆盖时，程序终止。
# - 值未指定时，使用回退值。
#
# Average time per character (unit: ms).
#
# - If the value is nan, inf, negative, or zero, and is not overridden,
#   the program aborts.
# - If the value is unspecified, the fallback value is used.
mean = 100

# 每字符用时标准差（单位：毫秒）。
#
# - 值为 nan、inf 或负数，且未被覆盖时，程序终止。
# - 值未指定时，使用回退值。
#
# Standard deviation of time per character (unit: ms).
#
# - If the value is nan, inf, or negative, and is not overridden,
#   the program aborts.
# - If the value is unspecified, the fallback value is used.
stddev = 100

[messages]
# 捕获 SIGINT 信号时显示的消息。
#
# - 值未指定时，使用回退值。
#
# Message displayed when catching the SIGINT signal.
#
# - If the value is unspecified, the fallback value is used.
interrupt = "呐、桥豆麻袋 …… 已经「厌烦」吾辈了嘛？"

[[quote]]
# 语录权重（可选字段）。
#
# - 值为 nan、inf、负数或零时，权重无效，语录不会被选取。
# - 值未指定时，权重设为有效权重的平均值；所有权重均无效时，权重设为一。
# - 权重总和为零或溢出时，程序中止。
#
# The quote weight (optional field).
#
# - If the value is nan, inf, negative, or zero, the weight is invalid,
#   and the quote is not selected.
# - If the value is unspecified, the weight is set to the average of valid
#   weights; if all weights are invalid, it is set to one.
# - If the sum of weights is zero or overflows, the program aborts.
weight = 1

# 语录本体。
#
# The quote itself.
content = """
诶多 …… ☆ 是 ♡ 同 ♡ 类 ♡ 呢 ♡ 喵 ♪（由乃逆光捧脸.jpg）
那群八嘎是不会懂的呀 …… 关于「二次元の美好」♡
呐，如果说吾の存在有意义的话、那一定是因为「二·次·元」吧 ☆ ？
所以呢 —— 妄图污染这份「爱」的人类、都会被吾「抹」「杀」「掉」喔 ♪
（小声）嘛 …… 讨厌二次元的八嘎三次元最恶心了啊魂淡！★
"""

[[quote]]
weight = 1
content = """
呐、二次元の民那 …… 都·是·最·最·善·良·の·存·在·呐 ☆
多洗忒 …… 要「嘲笑」这样的孩子呢？吾辈不明白啊 ——
嘛 …… 说到底，你们都只是污秽の「来自三次元的大人」吧？
大人什么的、最·讨·厌·了 ★ ♪
"""

[[quote]]
weight = 1
content = """
啊嘞啊嘞 QAQ？多洗忒 …… 欧尼酱 ww？
呐、桥豆麻袋 …… 已经「厌烦」吾辈了嘛？
哼唧 …… 真是「冷·酷·の·人」呢 QuQ —— ☆(๑°⌓°๑)
嘛 …… 即便是这样的瓦塔西，一定也是有「存·在·の·意·义」的吧、内 ~ ★
快来「肯定」啊？不然呀 …… 咱可就要「黑化」了哦 ♪ 呐？
"""

[[quote]]
weight = 1
content = """
呐。。。（伸出的小手又迅速垂下去）
嗦嘎（表情有点失落），米娜桑已经不喜欢了呀（紧咬嘴唇）
得磨，米娜桑忘了当初吗（握紧小手）
莫以得丝（强忍住眼泪），已经大丈夫了呦（挤出笑脸）
瓦大喜瓦，滋多滋多，滋多滋多（语气越来越用力了）滋多戴斯给！！！
一滋嘛叠磨瓦撕裂嘛赛！！！至死都不会瓦斯裂嘛斯（认真的表情）
"""

[[quote]]
weight = 1
content = """
诶多 …… 看起来阁下对于「二·次·元」の理解、似·乎·满·是·谬·误·哦 ☆ ~
嘛，连最为基本の「礼♪义♪廉♪耻♪」都早已失去了啊 …… ♪（笑）
呐，我说啊 —— 这样の kimino、也有自称「二 ♡ 次 ♡ 元」の资格吗 ★ ？
fufufu —— 说到底、阁下已经「二·次·元·失·格」了吧？呐 ~ ♪
"""

[[quote]]
weight = 1
content = """
唔噗噗 ~ 汝等「劣·等·生·物」…… 也配去「妄想」吗？
呐、「真正的二次元」什么的 —— 吾辈看汝是一点都不懂啊 ☆（笑）
嘛嘛嘛 …… 不过看着汝试图伪装成「二次元」の可笑姿态，
倒是让吾辈对于「三·次·元·的·白·痴」稍微有了些许兴趣哦？★
"""

[[quote]]
weight = 1
content = """
哼！（跺了跺粉嫩的小脚，肉嘟嘟的小手交叉摆在胸前，小嘴一撅，
头抬得高高的撇向一边，一副生人勿近的模样。又怕你真的离开，偷偷侧过脑袋看你）
"""

[[quote]]
weight = 1
content = """
喜欢你啊！八嘎！
为什么察觉不到啊，八嘎八嘎八嘎，最讨人厌啦。
但又是那么喜欢你，suki，suki，daisuki。
笨蛋，再多看看我啊！毕竟人家，最喜欢你了啊。
"""
